### ISSUE TITLE
Bug: can't tile sideways

### ISSUE THREAD

**Issue by Mennaruuk** [linuxmint/hypnotix#109]
I can't tile Hypnotix to the right or left of my screen :(

**Comment by JosephMcc** [comment]
You have to provide more info for us to really even answer this. You aren't giving us anything. Not even the distro or desktop environment you are on. The ability to tile depends on your screen resolution. If the window cannot be resized to fit into the tile area then it won't work.

All I can say is that it tile fine here on Cinnamon with a 1080p monitor.

**Comment by Mennaruuk** [comment]
My apologies. I’m running latest Linux Mint Cinnamon (20.1). Laptop screen size is 15.6 in. For me, it only tiles maximally. No tiling to right or left.

**Comment by JosephMcc** [comment]
No problem. But I doubt this is a bug. Your screen size doesn't matter here. It's the actual resolution.

Let's say you have a screen res of 1200 wide by 900 tall. If the minimum size the window can be sized to horizontally is 605 pixels. You will not be able to tile it because it will not fit into one-half of your screen width, which is 600 pixels. That is just example numbers but you get the issue. The minimum width of the window can be determined by a lot of things like the widgets it contains, text strings, etc.

**Comment by Mennaruuk** [comment]
So my resolution is 1366 x 768 (16:9). I did notice that half of the application takes more than half of my display, and tiling can’t happen to the right or left.

Thank you for elucidating this!
