### ISSUE TITLE
Install on OpenSuse

### ISSUE THREAD

**Issue by nicolalandro** [linuxmint/hypnotix#204]
I try to install on OpenSuse Tubleweed as in the following:
```
$ wget https://github.com/linuxmint/hypnotix/releases/download/1.1/hypnotix_1.1_all.deb
$ sudo alien -r hypnotix_1.1_all.deb
$ sudo zypper install ./hypnotix-1.1-2.noarch.rpm
```
But when I run it I have an error:
```
$ hypnotix
File "/usr/lib/hypnotix/hypnotix.py", line 19, in <module>
    gi.require_version('XApp', '1.0')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace XApp not available
```
What lib I need? I try [python38-xapp](https://software.opensuse.org/package/python38-xapp) and xapps-common  but it does not seams correct.
Any suggestions?

**Comment by Axel-Erfurt** [comment]
https://linux-packages.com/arch-linux/package/xapp

**Comment by nicolalandro** [comment]
Thank for the link but opensuse use zypper I install xapps, and python-xapp and python38-xapp, xapps-common but the error is there.

**Comment by Axel-Erfurt** [comment]
Sorry I posted the wrong link,

there are [hypnotix 2.6.1 rpm](https://software.opensuse.org//download.html?project=X11%3ACinnamon%3AFactory&package=hypnotix) and [xapps rpm](https://download.opensuse.org/repositories/X11:/Cinnamon:/Factory/openSUSE_Factory/src/xapps-2.2.8-98.3.src.rpm) on opensuse

**Comment by tabascosw** [comment]
When you install the above mentioned hypnotix rpm, it should pull in all necessary libs. The problem on Tumbleweed will be libmpv1, it is necessary for hypnotix to run, but is no longer available. Since the snapshot from 22.01.2022 TW provides libmpv2 only. 
You can still grab a copy of libmpv1 from the snapshot [archives](http://download.opensuse.org/history/).
I can build hypnotix against libmpv2 successfully but it won't run and I haven't had the time to investigate further.

**Comment by nicolalandro** [comment]
I solved in this way:
I install from experimental [X11:Cinnamon:Factory](https://software.opensuse.org/package/hypnotix)
and after I also run:
```
python3 -m pip install Unidecode
```
In this way it works!
