### ISSUE TITLE
If both Koreas are available, why isn't South Korea marked as South Korea, while North Korea is marked as North Korea?

### ISSUE THREAD

**Issue by ignxcy** [linuxmint/hypnotix#344]

**Comment by aldrinzigmundv** [comment]
Hi. The issue is related to the [Free-TV/IPTV](https://github.com/Free-TV/IPTV) project, which serves as the default IPTV provider for Hypnotix. As per the guidelines outlined in the README file, any concerns regarding TV channels or media content should be directed to the Free-TV/IPTV repository. Thank you.

**Comment by ignxcy** [comment]
Oh, okay
