### ISSUE TITLE
Fails to load videos on Wayland. Exception

### ISSUE THREAD

**Issue by lexcroftdev1** [linuxmint/hypnotix#90]
It works fine on X11 but does not work on wayland. Workaround on wayland is to run from command prompt as: 
GDK_BACKEND=x11 hypnotix

however the video screen pops out of the main app. 

Exception log: 
 
ree-IPTV: Getting playlist…
Free-IPTV: Checking playlist…
Free-IPTV: Loading channels…
All chanels: Getting playlist…
All chanels: Checking playlist…
All chanels: Loading channels…
Traceback (most recent call last):
File “/usr/lib/hypnotix/hypnotix.py”, line 1018, in on_mpv_drawing_area_realize
self.reinit_mpv()
File “/usr/lib/hypnotix/hypnotix.py”, line 1039, in reinit_mpv
input_vo_keyboard=True,osc=True, ytdl=True, wid=str(self.mpv_drawing_area.get_window().get_xid()))
AttributeError: ‘GdkWaylandWindow’ object has no attribute ‘get_xid’
CHANNEL: ‘Blomberg US’ (us_live.m3u8)
Exception in thread Thread-3:
Traceback (most recent call last):
File “/usr/lib/python3.9/threading.py”, line 954, in _bootstrap_inner
self.run()
File “/usr/lib/python3.9/threading.py”, line 892, in run
self._target(*self._args, **self._kwargs)
File “/usr/lib/hypnotix/hypnotix.py”, line 591, in play_async
self.reinit_mpv()
File “/usr/lib/hypnotix/hypnotix.py”, line 1039, in reinit_mpv
input_vo_keyboard=True,osc=True, ytdl=True, wid=str(self.mpv_drawing_area.get_window().get_xid()))
AttributeError: ‘GdkWaylandWindow’ object has no attribute ‘get_xid’

**Comment by ckorder** [comment]
if you want to make your life hard use wayland. if you want to fix this use firejail --x11 hypnotix ;D

**Comment by spagoc** [comment]
In order to run hypnotix in wayland with:
$ GDK_BACKEND=x11 hypnotix

just add the following line at hypnotix.py (.deb installs it in "/usr/lib/hypnotix", get write privilege on the file)  at row 1037:
          options["vo"] = "x11"

after the 1036 line:
        options["referrer"] = self.settings.get_string("http-referer")
  
Explanation:
with "$ GDK_BACKEND=x11 hypnotix" hypnotix is forced to run in xwayland but when it launchs mpv this run in Wayland and you get the error: "AttributeError: ‘GdkWaylandWindow’ object has no attribute ‘get_xid’". With "mpv -vo=x11 ..." mpv is forced to run in the x11 environment too.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/hypnotix/issues/33
